name: Run Crawler Every Minute

on:
  schedule:
    - cron: '*/1 * * * *'  # Cette ligne permet d'exécuter le workflow toutes les minutes

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Utiliser Python 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pymongo

      - name: Run crawler
        run: python crawler.py
